### ISSUE TITLE
Scroll position on width change

### ISSUE THREAD

**Issue by dlford** [lannex/react-overflow-wrapper#4]
I found one minor issue, when using this package in Gatsby, it may also be present in plain React but I haven't tested this.  When resizing the window after scrolling in the overflow wrapper, some items remain out of view with no way to bring them back unless you resize the window again to bring back the scroll icons.

Steps to reproduce:

1) Create an unsorted list inside the `<OverflowWrapper>`
2) Resize browser window to show scroll icons
3) Scroll away from the default position
4) Resize browser back to wide view to hide scroll icons

By the way, thank you for sharing this, it's really great!

**Comment by lannex** [comment]
This issue has been resolved.
Thanks for letting me know.
